name: Technical Home
favicon: null
layout_spectrum: 0.4261190677061677
typography_spectrum: 0.04078718298114836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5022227102890611
  lightness: 0.9030358598101884
  saturation: 0.776188513962552
  rhythmicContrast: 0.847440900746733
purpose: []
